name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Lint
      shell: bash -l {0} 
      run: |
        nvm install && \
        nvm use && \
        npm install
        # TODO: enable linting as well
        # && \
        #npm run lint

    - name: Test
      run: |
        npm run test
